TESTS: fix residual value tests after int16 conversion

diff --git a/tests/smresvalue.sh.in b/tests/smresvalue.sh.in
--- a/tests/smresvalue.sh.in
+++ b/tests/smresvalue.sh.in
@@ -6,6 +6,12 @@ SMENCFLAGS="-O0 --no-attack"
 WAV2ASCII=@top_builddir@/tools/wav2ascii
 DELTA=@top_srcdir@/tools/delta.py
 
+die()
+{
+  echo "$0: $@"
+  exit 1
+}
+
 if test -f "@srcdir@/$1"; then
   WAV="@srcdir@/$1"
 elif test -f "@top_builddir@/tests/$1"; then
@@ -17,14 +23,17 @@ fi
 START="$2"
 STOP="$3"
 RATE="$4"
+FREQ="$5"
+
+test -z "$FREQ" && die "freq parameter missing"
 
 SM=$(echo "$1" | sed s/.wav$/.sm/g)
 DWAV=$(echo "$1" | sed s/.wav$/-dec.wav/g)
 TWAV=$(echo "$1" | sed s/.wav$/.txt/g)
 TDWAV=$(echo "$1" | sed s/.wav$/-dec.txt/g)
 
-$SMENC $SMENCFLAGS $WAV $SM
-$SMPLAY $SM --no-noise --rate=$RATE --export $DWAV
+$SMENC $SMENCFLAGS -f $FREQ $WAV $SM || die "smenc failed"
+$SMPLAY $SM --no-noise --rate=$RATE --export $DWAV || die "smplay failed"
 $WAV2ASCII $WAV > $TWAV
 $WAV2ASCII $DWAV > $TDWAV
 $DELTA $TWAV $TDWAV | LANG=C awk 'FNR > '$START' && FNR < '$STOP' { r += $1 * $1; c += 1 } END { print "'$1' residual value:",r/c; if (r/c > 5e-8) exit(1); else exit (0);}' || exit 1
